package ExceptionDemo1;

public class ExceptionDemo2 {

	public static void main(String[] args) 
	{
		System.out.println("Main method invoking");
		System.out.println(10/0);
		System.out.println("done");
	}

}
